export enum QueryTitle {
  Genres = 'popular genres',
  SearchMovie = 'search movie list',
  Popular = 'popular movies sidebar',
  Favorite = 'favorite movies sidebar',
  CountUsers = 'count users',
  SearchUser = 'search users list',
  DeleteUser = 'delete user',
  DeleteMovie = 'delete movie',
  DeleteGenre = 'delete genre',
  DeleteActor = 'delete actor',
  SearchActor = 'search actor list',
  SearchGenre = 'search genre list',
  SearchAdminMovie = 'search admin movie list',
  Genre = 'genre',
  Movie = 'movie',
  Actor = 'actor',
  UpdateGenre = 'update genre',
  CreateGenre = 'create genre',
  CreateMovie = 'create movie',
  CreateActor = 'create actor',
  UpdateMovie = 'update movie',
  UpdateActor = 'update actor',
}
