export const ToastConfig = {
  Limit: 3,
  Delay: 4000,
  Newest: false,
  Position: 'top-right',
};

export enum ToastMessages {
  Registration = 'Registration completed successfully',
  Login = 'Login completed successfully',
  JWT = 'Your authorization is finished, plz sign in',
  Error = 'Error required',
  ErrorUserList = 'Error user list',
  ErrorDeleteUser = 'Error delete user',
  DeleteUser = 'delete is successful',
  ErrorMovieList = 'Error movie list',
  ErrorDeleteMovie = 'Error delete movie',
  DeleteMovie = 'delete is successful',
  ErrorActorList = 'Error actor list',
  ErrorDeleteActor = 'Error delete actor',
  DeleteActor = 'delete is successful',
  ErrorGenreList = 'Error genre list',
  ErrorDeleteGenre = 'Error delete genre',
  DeleteGenre = 'delete is successful',
  ErrorGetGenre = 'Get genre',
  ErrorUpdateGenre = 'Update genre',
  UpdateGenre = 'Genre update is successful',
  CreateGenre = 'create genre is successful',
  ErrorCreateGenre = 'Create genre',
  CreateMovie = 'create movie is successful',
  ErrorCreateMovie = 'Create movie',
  CreateActor = 'create actor is successful',
  ErrorCreateActor = 'Create actor',
  ErrorGetActor = 'Get actor',
  ErrorUpdateActor = 'Update actor',
  UpdateActor = 'Actor update is successful',
  ErrorGetMovie = 'Get movie',
  ErrorUpdateMovie = 'Update movie',
  UpdateMovie = 'Movie update is successful',
  UploadFile = 'Upload file is successful',
  ErrorUploadFile = 'Upload file',
  ErrorProfile = 'GetProfile',
  ErrorUpdateProfile = 'Error Updating profile',
  UpdateProfile = 'Profile update is successful',
  ErrorGetUser = 'Get user',
  ErrorGetRating = 'Get rating',
  ErrorSetRating = 'Set rating',
  SuccessRate = 'You have successfully rated!',
  ErrorUpdateFavorite = 'Update favorite',
}
